In [1]:
import numpy as np
from numpy import linalg as la
import copy

In [2]:
A = np.array([[1, 2, 3], [4, 2, 1], [19, 12, -8], [7, 100, -1]])
B = np.array([[1, 2], [4, 2], [19, 12], [7, 100]])

In [3]:
laqr = la.qr(B) 

## Classical Schmidt Algorithm

In [9]:
def classical_Schmidt_algorithm(A):
    m = A.shape[0]
    n = A.shape[1]
    Q = copy.deepcopy(A.astype(float)) 
    R = np.array([np.zeros(n) for i in range(n)])
    
    s = 0
    
    for k in range(n):
        for i in range(k):
            s = 0
            
            for j in range(m):
                s = s + Q[j, i] * Q[j, k]
            R[i, k] = s
            
            for j in range(m):
                Q[j, k] = Q[j, k] - Q[j, i] * R[i, k]
        
        s = 0
        for j in range(m):
            s = s + Q[j, k]**2
        R[k, k] = np.sqrt(s)
        
        for j in range(m):
            Q[j, k] = Q[j, k] / R[k, k]
    return Q, R

In [21]:
Q, R = classical_Schmidt_algorithm(B) 

In [22]:
Q

array([[ 0.04839339, -0.00218694],
       [ 0.19357357, -0.07544955],
       [ 0.91947445, -0.33059295],
       [ 0.33875374,  0.94075017]])

In [23]:
R

array([[20.66397832, 45.39300155],
       [ 0.        , 89.9526287 ]])

In [24]:
Q.dot(R) 

array([[  1.,   2.],
       [  4.,   2.],
       [ 19.,  12.],
       [  7., 100.]])

## Modified Gram Schmidt

In [25]:
def modified_Gram_Schmidt(A):
    m = A.shape[0]
    n = A.shape[1]
    Q = copy.deepcopy(A.astype(float)) 
    R = np.array([np.zeros(n) for i in range(n)])
    
    for k in range(n):
        s = 0
        for j in range(m):
            s += Q[j, k]**2
        
        R[k, k] = np.sqrt(s)
        
        for j in range(m):
            Q[j, k] = Q[j, k] / R[k, k]
        
        for i in range(k+1, n):
            s = 0
            
            for j in range(m):
                s += Q[j, i] * Q[j, k]
            
            R[k, i] = s
            
            for j in range(m):
                Q[j, i] = Q[j, i] - R[k, i] * Q[j, k]

    return Q, R

In [26]:
Qm, Rm = modified_Gram_Schmidt(A) 

In [27]:
Qm

array([[ 0.04839339, -0.00218694,  0.78615752],
       [ 0.19357357, -0.07544955,  0.5958489 ],
       [ 0.91947445, -0.33059295, -0.16388063],
       [ 0.33875374,  0.94075017, -0.00797445]])

In [28]:
Rm

array([[20.66397832, 45.39300155, -7.35579556],
       [ 0.        , 89.9526287 ,  1.62198305],
       [ 0.        ,  0.        ,  4.27334092]])

In [29]:
Qm.dot(Rm)

array([[  1.,   2.,   3.],
       [  4.,   2.,   1.],
       [ 19.,  12.,  -8.],
       [  7., 100.,  -1.]])

## Reorthogonalization 

In [30]:
def reorthogonalization(A):
    m = A.shape[0]
    n = A.shape[1]
    Q = copy.deepcopy(A.astype(float)) 
    R = np.array([np.zeros(n) for i in range(n)])
    
    
    for k in range(n):
        t = 0
        tt = 0
        
        for j in range(m):
            t += Q[j, k]**2


        while True:
            for i in range(k):
                s = 0
                for j in range(m):
                    s += Q[j, i] * Q[j, k]
                    
                if tt == 0:
                    R[i, k] = s
                    
                for j in range(m):
                    Q[j, k] -= s*Q[j, i]
            
            tt = 0
            for j in range(m):
                tt += Q[j, k]**2
            
            if tt < t/100:
                t = tt
            else:
                break
        R[k, k] = np.sqrt(tt)

        for j in range(m):
            Q[j, k] = Q[j, k] / R[k, k]
    return Q, R

In [31]:
Qr, Rr = reorthogonalization(A) 

In [32]:
Qr

array([[ 0.04839339, -0.00218694,  0.78615752],
       [ 0.19357357, -0.07544955,  0.5958489 ],
       [ 0.91947445, -0.33059295, -0.16388063],
       [ 0.33875374,  0.94075017, -0.00797445]])

In [33]:
Rr

array([[20.66397832, 45.39300155, -7.35579556],
       [ 0.        , 89.9526287 ,  1.62198305],
       [ 0.        ,  0.        ,  4.27334092]])

In [34]:
Qr.dot(Rr) 

array([[  1.,   2.,   3.],
       [  4.,   2.,   1.],
       [ 19.,  12.,  -8.],
       [  7., 100.,  -1.]])