In [1]:
import numpy as np
from numpy import linalg as la
import copy

In [47]:
A = np.array([
              [1, 2, 3], 
              [4, 2, 1], 
              [19, 12, -8], 
              [7, 100, -1]
            ])  

In [52]:
B = np.array([
              [15.3, 18.4, -192.1, 50.0], 
              [900.3, 510.1, 246.1, 741.9], 
              [109, -12.5, -8.1, 15.5], 
              [180, -651.1, 852.7, 2003.9],
              [85.2, 16.4, -5.2, 19.2]
             ]) 

In [97]:
C = 200*np.random.random_sample((6, 4)) - 100  

In [98]:
C

array([[ 64.99918469,  12.24666546, -94.79928714, -37.38040955],
       [-91.31316505,  62.94100901, -14.2887801 ,  17.07789134],
       [ 68.9306603 ,  20.66498986,  84.67540034,  36.32856451],
       [-44.08363725,  -8.05846585, -33.13885347,  61.23181886],
       [-39.90585863, -86.13945322, -23.91922931,  52.34589085],
       [ 85.66254135, -47.78976248,   7.89245575, -67.31636365]])

## Classical Schmidt Algorithm

In [56]:
def classical_Schmidt_algorithm(A):
    m = A.shape[0]
    n = A.shape[1]
    Q = copy.deepcopy(A.astype(float)) 
    R = np.array([np.zeros(n) for i in range(n)])
    
    s = 0
    
    for k in range(n):
        for i in range(k):
            s = 0
            
            for j in range(m):
                s = s + Q[j, i] * Q[j, k]
            R[i, k] = s
            
            for j in range(m):
                Q[j, k] = Q[j, k] - Q[j, i] * R[i, k]
        
        s = 0
        for j in range(m):
            s = s + Q[j, k]**2
        R[k, k] = np.sqrt(s)
        
        for j in range(m):
            Q[j, k] = Q[j, k] / R[k, k]
    return Q, R

In [62]:
Q, R = classical_Schmidt_algorithm(A)  

In [63]:
Q

array([[ 0.04839339, -0.00218694,  0.78615752],
       [ 0.19357357, -0.07544955,  0.5958489 ],
       [ 0.91947445, -0.33059295, -0.16388063],
       [ 0.33875374,  0.94075017, -0.00797445]])

In [64]:
R

array([[20.66397832, 45.39300155, -7.35579556],
       [ 0.        , 89.9526287 ,  1.62198305],
       [ 0.        ,  0.        ,  4.27334092]])

In [65]:
Q.dot(R) 

array([[  1.,   2.,   3.],
       [  4.,   2.,   1.],
       [ 19.,  12.,  -8.],
       [  7., 100.,  -1.]])

In [66]:
A

array([[  1,   2,   3],
       [  4,   2,   1],
       [ 19,  12,  -8],
       [  7, 100,  -1]])

## Modified Gram Schmidt

In [67]:
def modified_Gram_Schmidt(A):
    m = A.shape[0]
    n = A.shape[1]
    Q = copy.deepcopy(A.astype(float)) 
    R = np.array([np.zeros(n) for i in range(n)])
    
    for k in range(n):
        s = 0
        for j in range(m):
            s += Q[j, k]**2
        
        R[k, k] = np.sqrt(s)
        
        for j in range(m):
            Q[j, k] = Q[j, k] / R[k, k]
        
        for i in range(k+1, n):
            s = 0
            
            for j in range(m):
                s += Q[j, i] * Q[j, k]
            
            R[k, i] = s
            
            for j in range(m):
                Q[j, i] = Q[j, i] - R[k, i] * Q[j, k]

    return Q, R

In [68]:
Qm, Rm = modified_Gram_Schmidt(B)  

In [69]:
Qm

array([[ 0.01647626,  0.01663528, -0.81709036,  0.57584656],
       [ 0.96951487,  0.206036  ,  0.08967833,  0.09277323],
       [ 0.1173799 , -0.07527863, -0.50146756, -0.72427369],
       [ 0.19383836, -0.97521914,  0.05011402,  0.09390553],
       [ 0.09175016, -0.02352009, -0.26521689, -0.35553234]])

In [70]:
Rm

array([[  928.60875507,   368.68199673,   399.29061402,  1112.12058292],
       [    0.        ,   740.92548565,  -783.32747637, -1802.17016822],
       [    0.        ,     0.        ,   227.20614059,   113.23641894],
       [    0.        ,     0.        ,     0.        ,   267.74562041]])

In [71]:
Qm.dot(Rm)

array([[  15.3,   18.4, -192.1,   50. ],
       [ 900.3,  510.1,  246.1,  741.9],
       [ 109. ,  -12.5,   -8.1,   15.5],
       [ 180. , -651.1,  852.7, 2003.9],
       [  85.2,   16.4,   -5.2,   19.2]])

In [72]:
B

array([[  15.3,   18.4, -192.1,   50. ],
       [ 900.3,  510.1,  246.1,  741.9],
       [ 109. ,  -12.5,   -8.1,   15.5],
       [ 180. , -651.1,  852.7, 2003.9],
       [  85.2,   16.4,   -5.2,   19.2]])

## Reorthogonalization 

In [73]:
def reorthogonalization(A):
    m = A.shape[0]
    n = A.shape[1]
    Q = copy.deepcopy(A.astype(float)) 
    R = np.array([np.zeros(n) for i in range(n)])
    
    
    for k in range(n):
        t = 0
        tt = 0
        
        for j in range(m):
            t += Q[j, k]**2


        while True:
            for i in range(k):
                s = 0
                for j in range(m):
                    s += Q[j, i] * Q[j, k]
                    
                if tt == 0:
                    R[i, k] = s
                    
                for j in range(m):
                    Q[j, k] -= s*Q[j, i]
            
            tt = 0
            for j in range(m):
                tt += Q[j, k]**2
            
            if tt < t/100:
                t = tt
            else:
                break
        R[k, k] = np.sqrt(tt)

        for j in range(m):
            Q[j, k] = Q[j, k] / R[k, k]
    return Q, R

In [99]:
Qr, Rr = reorthogonalization(C)  

In [100]:
Qr

array([[ 0.38714456,  0.17947025, -0.82099793,  0.26309728],
       [-0.54387444,  0.43042563, -0.06976595, -0.13936267],
       [ 0.410561  ,  0.25571091,  0.53399581,  0.59989055],
       [-0.26256853, -0.11961265, -0.18733927,  0.54805642],
       [-0.23768507, -0.77975007, -0.02744988,  0.26439356],
       [ 0.51021851, -0.30792657,  0.00970034, -0.42569873]])

In [101]:
Rr

array([[167.89383451, -22.79979647,  24.24803166, -71.71019916],
       [  0.        , 117.42047602,  18.67306475, -17.48061465],
       [  0.        ,   0.        , 130.98454532,  35.33608064],
       [  0.        ,   0.        ,   0.        ,  85.63335558]])

In [102]:
Qr.dot(Rr) 

array([[ 64.99918469,  12.24666546, -94.79928714, -37.38040955],
       [-91.31316505,  62.94100901, -14.2887801 ,  17.07789134],
       [ 68.9306603 ,  20.66498986,  84.67540034,  36.32856451],
       [-44.08363725,  -8.05846585, -33.13885347,  61.23181886],
       [-39.90585863, -86.13945322, -23.91922931,  52.34589085],
       [ 85.66254135, -47.78976248,   7.89245575, -67.31636365]])

In [103]:
C

array([[ 64.99918469,  12.24666546, -94.79928714, -37.38040955],
       [-91.31316505,  62.94100901, -14.2887801 ,  17.07789134],
       [ 68.9306603 ,  20.66498986,  84.67540034,  36.32856451],
       [-44.08363725,  -8.05846585, -33.13885347,  61.23181886],
       [-39.90585863, -86.13945322, -23.91922931,  52.34589085],
       [ 85.66254135, -47.78976248,   7.89245575, -67.31636365]])