In [1]:
import numpy as np
from numpy import linalg as la
from scipy import linalg as las
import copy

In [2]:
A = np.array([
              [1, 2, 3], 
              [4, 2, 1], 
              [19, 12, -8], 
              [7, 100, -1]
            ])  

In [3]:
B = np.array([
              [15.3, 18.4, -192.1, 50.0], 
              [900.3, 510.1, 246.1, 741.9], 
              [109, -12.5, -8.1, 15.5], 
              [180, -651.1, 852.7, 2003.9],
              [85.2, 16.4, -5.2, 19.2]
             ]) 

In [4]:
C = 0.0000000002*np.random.random_sample((100, 50)) - 0.0000000001  

In [5]:
C

array([[ 7.80356609e-11, -8.91091273e-11, -4.47621070e-11, ...,
        -2.81551653e-13,  1.17413328e-11,  8.35820170e-11],
       [-7.70746028e-11, -9.70873885e-11, -3.62680629e-11, ...,
         8.06045619e-11,  5.97234979e-11, -9.51625888e-11],
       [-4.81422633e-12,  6.36725141e-11, -2.73111159e-12, ...,
         4.31626049e-11, -9.19183260e-11,  3.87998952e-11],
       ...,
       [ 4.03935037e-11, -9.73681489e-11, -9.68018203e-11, ...,
         4.58950211e-11,  4.79310169e-11,  4.12411338e-11],
       [ 1.35122360e-13, -4.34836727e-11,  2.61057892e-11, ...,
         7.01069111e-11,  9.86670379e-12,  2.79345218e-11],
       [-9.64102058e-11, -9.72602466e-12,  4.64622810e-11, ...,
        -7.44640762e-12, -2.53996563e-11,  3.97195419e-11]])

In [6]:
H = las.hilbert(10)        

In [7]:
H

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
        0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714,
        0.125     , 0.11111111, 0.1       , 0.09090909, 0.08333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ,
        0.11111111, 0.1       , 0.09090909, 0.08333333, 0.07692308],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
        0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
        0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667],
       [0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909,
        0.08333333, 0.07692308, 0.07142857, 0.06666667, 0.0625    ],
       [0.125     , 0.11111111, 0.1      

## Classical Schmidt Algorithm

In [8]:
def classical_Schmidt_algorithm(A):
    m = A.shape[0]
    n = A.shape[1]
    Q = copy.deepcopy(A.astype(float)) 
    R = np.array([np.zeros(n) for i in range(n)])
    
    s = 0
    
    for k in range(n):
        for i in range(k):
            s = 0
            
            for j in range(m):
                s = s + Q[j, i] * Q[j, k]
            R[i, k] = s
            
            for j in range(m):
                Q[j, k] = Q[j, k] - Q[j, i] * R[i, k]
        
        s = 0
        for j in range(m):
            s = s + Q[j, k]**2
        R[k, k] = np.sqrt(s)
        
        for j in range(m):
            Q[j, k] = Q[j, k] / R[k, k]
    return Q, R

In [9]:
A = np.array([
              [1, 2, 3], 
              [4, 2, 1], 
              [19, 12, -8]
            ])   

In [10]:
Q, R = classical_Schmidt_algorithm(H)       

In [101]:
H1 = Q.dot(R) 

In [11]:
Q.dot(Q.T) 

array([[ 1.00000001e+00, -1.62515285e-08,  2.44935574e-07,
        -2.21022841e-06,  1.02418562e-05, -2.75544154e-05,
         4.43468542e-05, -4.21617201e-05,  2.18126620e-05,
        -4.73933348e-06],
       [-1.62515285e-08,  1.00000002e+00, -1.61976629e-07,
         1.61432857e-06, -7.58483024e-06,  2.08305185e-05,
        -3.40636943e-05,  3.28736357e-05, -1.72188777e-05,
         3.79072293e-06],
       [ 2.44935574e-07, -1.61976629e-07,  9.99999537e-01,
         1.89466919e-06, -1.02321136e-05,  2.73222823e-05,
        -4.51448527e-05,  4.32523450e-05, -2.28587317e-05,
         4.88539724e-06],
       [-2.21022841e-06,  1.61432857e-06,  1.89466919e-06,
         1.00000406e+00, -7.80530772e-06,  2.80078717e-05,
        -4.18066663e-05,  4.29668545e-05, -2.07493714e-05,
         5.80953117e-06],
       [ 1.02418562e-05, -7.58483024e-06, -1.02321136e-05,
        -7.80530772e-06,  9.99982707e-01,  1.60914126e-05,
        -4.56242221e-05,  3.15607566e-05, -2.50165341e-05,
        -4.

## Modified Gram Schmidt

In [12]:
def modified_Gram_Schmidt(A):
    m = A.shape[0]
    n = A.shape[1]
    Q = copy.deepcopy(A.astype(float)) 
    R = np.array([np.zeros(n) for i in range(n)])
    
    for k in range(n):
        s = 0
        for j in range(m):
            s += Q[j, k]**2
        
        R[k, k] = np.sqrt(s)
        
        for j in range(m):
            Q[j, k] = Q[j, k] / R[k, k]
        
        for i in range(k+1, n):
            s = 0
            
            for j in range(m):
                s += Q[j, i] * Q[j, k]
            
            R[k, i] = s
            
            for j in range(m):
                Q[j, i] = Q[j, i] - R[k, i] * Q[j, k]

    return Q, R

In [13]:
Qm, Rm = modified_Gram_Schmidt(H)     

In [15]:
Qm.dot(Rm) 

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
        0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714,
        0.125     , 0.11111111, 0.1       , 0.09090909, 0.08333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ,
        0.11111111, 0.1       , 0.09090909, 0.08333333, 0.07692308],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
        0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
        0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667],
       [0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909,
        0.08333333, 0.07692308, 0.07142857, 0.06666667, 0.0625    ],
       [0.125     , 0.11111111, 0.1      

In [16]:
Qm.dot(Qm.T) 

array([[ 1.00000001e+00, -1.62515285e-08,  2.44935574e-07,
        -2.21022841e-06,  1.02418562e-05, -2.75544154e-05,
         4.43468542e-05, -4.21617201e-05,  2.18126620e-05,
        -4.73933348e-06],
       [-1.62515285e-08,  1.00000002e+00, -1.61976629e-07,
         1.61432857e-06, -7.58483024e-06,  2.08305185e-05,
        -3.40636943e-05,  3.28736357e-05, -1.72188777e-05,
         3.79072293e-06],
       [ 2.44935574e-07, -1.61976629e-07,  9.99999537e-01,
         1.89466919e-06, -1.02321136e-05,  2.73222823e-05,
        -4.51448527e-05,  4.32523450e-05, -2.28587317e-05,
         4.88539724e-06],
       [-2.21022841e-06,  1.61432857e-06,  1.89466919e-06,
         1.00000406e+00, -7.80530772e-06,  2.80078717e-05,
        -4.18066663e-05,  4.29668545e-05, -2.07493714e-05,
         5.80953117e-06],
       [ 1.02418562e-05, -7.58483024e-06, -1.02321136e-05,
        -7.80530772e-06,  9.99982707e-01,  1.60914126e-05,
        -4.56242221e-05,  3.15607566e-05, -2.50165341e-05,
        -4.

## Reorthogonalization 

In [17]:
def reorthogonalization(A):
    m = A.shape[0]
    n = A.shape[1]
    Q = copy.deepcopy(A.astype(float)) 
    R = np.array([np.zeros(n) for i in range(n)])
    
    
    for k in range(n):
        t = 0
        tt = 0
        
        for j in range(m):
            t += Q[j, k]**2


        while True:
            for i in range(k):
                s = 0
                for j in range(m):
                    s += Q[j, i] * Q[j, k]
                    
                if tt == 0:
                    R[i, k] = s
                    
                for j in range(m):
                    Q[j, k] -= s*Q[j, i]
            
            tt = 0
            for j in range(m):
                tt += Q[j, k]**2
            
            if tt < t/100:
                t = tt
            else:
                break
        R[k, k] = np.sqrt(tt)

        for j in range(m):
            Q[j, k] = Q[j, k] / R[k, k] 
    return Q, R

In [18]:
Qr, Rr = reorthogonalization(H)     

In [19]:
Qr.dot(Rr) 

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
        0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714,
        0.125     , 0.11111111, 0.1       , 0.09090909, 0.08333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ,
        0.11111111, 0.1       , 0.09090909, 0.08333333, 0.07692308],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
        0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
        0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667],
       [0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909,
        0.08333333, 0.07692308, 0.07142857, 0.06666667, 0.0625    ],
       [0.125     , 0.11111111, 0.1      

In [20]:
Qr.dot(Qr.T) 

array([[ 1.00000000e+00,  3.20559056e-17,  1.07171179e-16,
         1.81321312e-16,  2.19218665e-16,  1.55340125e-16,
         1.16615155e-16,  1.37683829e-16,  1.16134199e-16,
         8.55706300e-17],
       [ 3.20559056e-17,  1.00000000e+00,  3.01278396e-16,
         2.56657759e-16,  1.60709255e-16,  1.31174910e-16,
         1.31933852e-16,  9.88792381e-17,  5.98750650e-17,
         9.48727723e-17],
       [ 1.07171179e-16,  3.01278396e-16,  1.00000000e+00,
         1.13624388e-16,  1.90819582e-16,  1.76941795e-16,
         1.12540186e-16,  8.47846099e-17,  1.02999206e-16,
         1.90928003e-16],
       [ 1.81321312e-16,  2.56657759e-16,  1.13624388e-16,
         1.00000000e+00,  6.93889390e-17,  2.77555756e-17,
        -6.93889390e-18,  8.67361738e-17,  1.47451495e-16,
         7.58941521e-17],
       [ 2.19218665e-16,  1.60709255e-16,  1.90819582e-16,
         6.93889390e-17,  1.00000000e+00,  1.66533454e-16,
         9.71445147e-17,  8.32667268e-17,  4.16333634e-17,
         1.